#!/bin/bash

# Error handling
set -e

# Log script start
echo "Script started at $(date)"

# Fetch AWS credentials from Secrets Manager
AWS_CREDS=$(aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:us-east-1:244883884162:secret:terraform_user-RJI5cn --query SecretString --output text)


# Check if AWS credentials are present
if [ -z "$AWS_CREDS" ]; then
  echo "Error: Failed to retrieve AWS credentials from Secrets Manager."
  exit 1
fi

# Parse the JSON string
AWS_ACCESS_KEY_ID=$(echo "$AWS_CREDS" | jq -r .AWS_ACCESS_KEY_ID)
AWS_SECRET_ACCESS_KEY=$(echo "$AWS_CREDS" | jq -r .AWS_SECRET_ACCESS_KEY)
AWS_DEFAULT_REGION=$(echo "$AWS_CREDS" | jq -r .AWS_DEFAULT_REGION)

# Set AWS CLI configuration
aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
aws configure set default.region $AWS_DEFAULT_REGION

# Run the Quantum ESPRESSO command
# Configure -np with the desired number of processing cores
mpirun -np 4 /opt/qe-6.8/bin/pw.x -in /workdir/input.in > /workdir/output.out

# Copy all files generated by pw.x to S3
aws s3 cp /workdir/ s3://deborah-qe-test-bucket/results/ --recursive

# Log script end
echo "Script completed successfully at $(date)"