name: Build and Deploy

on:
  push:
    branches:
      - dev

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ AWS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print repository environment variable
        run: echo "Value of AWS_REGION is $AWS_REGION"

      # Add your build and deploy steps here
