name: Build and Deploy

on:
  push:
    branches:
      - dev

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID : ${{ secrets.AWS_ACCESS_KEY_ID  }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print repository environment variable
        run: echo "Value of AWS_ACCESS_KEY_ID  is $AWS_ACCESS_KEY_ID "

      # Add your build and deploy steps here
